### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by altysheff** [upgradeQ/OBS-Studio-Python-Scripting-Cheatsheet-obspython-Examples-of-API#10]
D:\Programms\obs-studio\data\obs-scripting\64bit> **python**
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> **import obspython**
Traceback (most recent call last):
  File "D:\Programms\obs-studio\data\obs-scripting\64bit\obspython.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Artur\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: Не найден указанный модуль.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programms\obs-studio\data\obs-scripting\64bit\obspython.py", line 17, in <module>
    _obspython = swig_import_helper()
  File "D:\Programms\obs-studio\data\obs-scripting\64bit\obspython.py", line 16, in swig_import_helper
    return importlib.import_module('_obspython')
  File "C:\Users\Artur\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: Не найден указанный модуль.
>>>

**Comment by upgradeQ** [comment]
@altysheff `import obspython` only works inside OBS Studio, add script via Tools > Scripts > "+" button.
Since you are on Windows you also must specify the path to Python 3.6.x (as of writing this OBS version 26.1.1)
